export const adminHistory = [
  {
    id: 1,
    type: "Deposit",
    name: "Anderson Banny",
    email: "andybanny@gmail.com",
    date: "16/02/2023",
    transId: "DP22078",
    amount: "NGN 200,000",
    action: "Approved",
  },
  {
    id: 2,
    type: "Deposit",
    name: "Anderson Banny",
    email: "andybanny@gmail.com",
    date: "16/02/2023",
    transId: "DP22078",
    amount: "NGN 200,000",
    action: "Approved",
  },
  {
    id: 3,
    type: "Deposit",
    name: "Anderson Banny",
    email: "andybanny@gmail.com",
    date: "16/02/2023",
    transId: "DP22078",
    amount: "NGN 200,000",
    action: "Approved",
  },
  {
    id: 4,
    type: "Deposit",
    name: "Anderson Banny",
    email: "andybanny@gmail.com",
    date: "16/02/2023",
    transId: "DP22078",
    amount: "NGN 200,000",
    action: "Approved",
  },
  {
    id: 5,
    type: "Deposit",
    name: "Anderson Banny",
    email: "andybanny@gmail.com",
    date: "16/02/2023",
    transId: "DP22078",
    amount: "NGN 200,000",
    action: "Approved",
  },
  {
    id: 6,
    type: "Deposit",
    name: "Anderson Banny",
    email: "andybanny@gmail.com",
    date: "16/02/2023",
    transId: "DP22078",
    amount: "NGN 200,000",
    action: "Approved",
  },
  {
    id: 7,
    type: "Deposit",
    name: "Anderson Banny",
    email: "andybanny@gmail.com",
    date: "16/02/2023",
    transId: "DP22078",
    amount: "NGN 200,000",
    action: "Approved",
  },
  {
    id: 8,
    type: "Deposit",
    name: "Anderson Banny",
    email: "andybanny@gmail.com",
    date: "16/02/2023",
    transId: "DP22078",
    amount: "NGN 200,000",
    action: "Approved",
  },
];
